# Generated by Django 5.0.4 on 2024-05-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmodule", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pcs", name="price", field=models.FloatField(default=0.0),
        ),
    ]
