# Generated by Django 5.0.4 on 2024-05-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmodule", "0003_cert_cartitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="cert", name="user",),
        migrations.AddField(
            model_name="pcs",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="CartItem",),
        migrations.DeleteModel(name="Cert",),
    ]
